export const GlobalVars = {
    "GRID_WIDTH": 45,
    "GRID_HEIGHT": 20,
    "GRID_ENEMY_PERCENTAGE": 2,
    "GRID_FOODCELL_PERCENTAGE": 10,
    "GRID_BLOCKADECELL_PERCENTAGE": 10,
    "GRID_DELAY": 50,
    "COLONY_START_ANTAMOUNT": 100,
    "COLONY_START_FOODAMOUNT": 0,
    "CELL_COSTS": 50,
    "GATHERER_MAXFOODAMOUNT": 2,
    "FOODCELL_MAXFOODAMOUNT": 10,
    "FOODCELL_MAXTURNSWITHOUTFOOD": 100,
    "ANT_MAXAGE_MIN": 80,
    "ANT_MAXAGE_MAX": 120,
    "GATHERER_CREATE_ANT_INTERVAL": 50,
    "GATHERER_CREATE_ANT_FOOD_COSTS": 20
}