export const GlobalVars = {
    "DEFAULT_CELL_COSTS": 50,
    "DEFAULT_COLONY_FOODAMOUNT": 0,
    "DEFAULT_ANT_MAXAGE_MIN": 80,
    "DEFAULT_ANT_MAXAGE_MAX": 120,
    "DEFAULT_GATHERER_MAXFOODAMOUNT": 2,
    "DEFAULT_FOODCELL_MAXFOODAMOUNT": 10,
    "DEFAULT_FOODCELL_MAXTURNSWITHOUTFOOD": 100,
    "CREATE_ANT_INTERVAL": 50,
    "CREATE_ANT_FOOD_COSTS": 20
}